languages:
  JavaScript: true

exclude_paths:
- "test/*"
- "gulpfile.js"
- "protractor.conf.js"
- "karma.conf.js"
- "dist/*"
- "website/*"

engines:
  eslint:
    enabled: true

ratings:
  paths:
  - src/**
